- platform: template
  name: Haustür
  value_template: "{{ is_state('switch.mb_haustur_dauer', 'off') and is_state('switch.mb_haustur_impuls', 'off') }}"
  optimistic: true
  lock:
    action: switch.turn_off
    target:
      entity_id: switch.mb_haustur_dauer
  unlock:
    action: switch.turn_on
    target:
      entity_id: switch.mb_haustur_dauer
  open:
    action: switch.turn_on
    target:
      entity_id: switch.mb_haustur_impuls
- platform: template
  name: Garage Haus
  value_template: "{{ is_state('switch.mb_turoffner_garage_haus', 'off') }}"
  optimistic: true
  lock:
    action: switch.turn_off
    target:
      entity_id: switch.mb_turoffner_garage_haus
  unlock:
    action: switch.turn_on
    target:
      entity_id: switch.mb_turoffner_garage_haus
  open:
    action: switch.turn_on
    target:
      entity_id: switch.mb_turoffner_garage_haus
- platform: template
  name: Garage Strasse
  value_template: "{{ is_state('switch.mb_turoffner_garage_strasse', 'off') }}"
  optimistic: true
  lock:
    action: switch.turn_off
    target:
      entity_id: switch.mb_turoffner_garage_strasse
  unlock:
    action: switch.turn_on
    target:
      entity_id: switch.mb_turoffner_garage_strasse
  open:
    action: switch.turn_on
    target:
      entity_id: switch.mb_turoffner_garage_strasse
- platform: template
  name: Werkstatt
  value_template: "{{ is_state('switch.mb_turoffner_werkstatt', 'off') }}"
  optimistic: true
  lock:
    action: switch.turn_off
    target:
      entity_id: switch.mb_turoffner_werkstatt
  unlock:
    action: switch.turn_on
    target:
      entity_id: switch.mb_turoffner_werkstatt
  open:
    action: switch.turn_on
    target:
      entity_id: switch.mb_turoffner_werkstatt
