- platform: template
  name: Haustür
  value_template: "{{ is_state('switch.mb_haustur_dauer', 'off') }}"
  optimistic: true
  lock:
    service: switch.turn_off
    target:
      entity_id: switch.mb_haustur_dauer
  unlock:
    service: switch.turn_on
    target:
      entity_id: switch.mb_haustur_dauer
