# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /config/www/community/lovelace-card-mod/card-mod.js

# Text to speech
tts:
  - platform: google_translate
#---------------------------------------------------------------
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 640
  currency: EUR
  country: DE
  unit_system: metric
  time_zone: "Europe/Berlin"

  #Workaround for Custom Sensors for Energy Dashboard
  customize_glob:
    sensor.*_energy:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: energy
      state_class: total_increasing
    sensor.trinkwasser:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: "water"
      state_class: total_increasing

# Web Access Config
http:
  server_port: 443

# ADS Config
ads:
  ip_address: !secret beckhoff_ip
  device: !secret beckhoff_ads_device
  port: !secret beckhoff_ads_port

#------------------ Other Includes ----------------------
light: !include_dir_merge_list custom_light
cover: !include_dir_merge_list custom_cover
sensor: !include_dir_merge_list custom_sensor
binary_sensor: !include_dir_merge_list custom_binarySensor
modbus: !include_dir_merge_list custom_modbus
lock: !include_dir_merge_list custom_lock
alarm_control_panel: !include_dir_merge_list custom_secPanel
notify: !include notify.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
climate: !include_dir_merge_list custom_climate

## Weather based template trigger to send esphome devices data
template:
  - trigger:
      - trigger: time_pattern
        minutes: "1"
    action:
      - action: weather.get_forecasts
        data:
          type: hourly
        target:
          entity_id: weather.freudenst
        response_variable: forecast_data
    sensor:
      - name: "Forecast (4h) Temperature"
        unique_id: forecast_4h_temperature
        state: >
          {{ forecast_data['weather.freudenst'].forecast[6].temperature }}
      - name: "Forecast (4h) Condition"
        unique_id: forecast_4h_condition
        state: >
          {{ forecast_data['weather.freudenst'].forecast[6].condition }}
      - name: "Forecast (4h) Wind Speed"
        unique_id: forecast_4h_wind_speed
        state: >
          {{ forecast_data['weather.freudenst'].forecast[6].wind_speed }}
      - name: "Forecast (4h) Wind Gust Speed"
        unique_id: forecast_4h_wind_gust_speed
        state: >
          {{ forecast_data['weather.freudenst'].forecast[6].wind_gust_speed }}
      - name: "Forecast (4h) Precipitation"
        unique_id: forecast_4h_precipitation
        state: >
          {{ forecast_data['weather.freudenst'].forecast[6].precipitation }}
      - name: "Forecast (4h) Timestamp"
        unique_id: forecast_4h_timestamp
        state: >
          {{ forecast_data['weather.freudenst'].forecast[6].datetime }}

      - name: "Forecast (8h) Temperature"
        unique_id: forecast_8h_temperature
        state: >
          {{ forecast_data['weather.freudenst'].forecast[10].temperature }}
      - name: "Forecast (8h) Condition"
        unique_id: forecast_8h_condition
        state: >
          {{ forecast_data['weather.freudenst'].forecast[10].condition }}
      - name: "Forecast (8h) Wind Speed"
        unique_id: forecast_8h_wind_speed
        state: >
          {{ forecast_data['weather.freudenst'].forecast[10].wind_speed }}
      - name: "Forecast (8h) Wind Gust Speed"
        unique_id: forecast_8h_wind_gust_speed
        state: >
          {{ forecast_data['weather.freudenst'].forecast[10].wind_gust_speed }}
      - name: "Forecast (8h) Precipitation"
        unique_id: forecast_8h_precipitation
        state: >
          {{ forecast_data['weather.freudenst'].forecast[10].precipitation }}
      - name: "Forecast (8h) Timestamp"
        unique_id: forecast_8h_timestamp
        state: >
          {{ forecast_data['weather.freudenst'].forecast[10].datetime }}

      - name: "Forecast (12h) Temperature"
        unique_id: forecast_12h_temperature
        state: >
          {{ forecast_data['weather.freudenst'].forecast[14].temperature }}
      - name: "Forecast (12h) Condition"
        unique_id: forecast_12h_condition
        state: >
          {{ forecast_data['weather.freudenst'].forecast[14].condition }}
      - name: "Forecast (12h) Wind Speed"
        unique_id: forecast_12h_wind_speed
        state: >
          {{ forecast_data['weather.freudenst'].forecast[14].wind_speed }}
      - name: "Forecast (12h) Wind Gust Speed"
        unique_id: forecast_12h_wind_gust_speed
        state: >
          {{ forecast_data['weather.freudenst'].forecast[14].wind_gust_speed }}
      - name: "Forecast (12h) Precipitation"
        unique_id: forecast_12h_precipitation
        state: >
          {{ forecast_data['weather.freudenst'].forecast[14].precipitation }}
      - name: "Forecast (12h) Timestamp"
        unique_id: forecast_12h_timestamp
        state: >
          {{ forecast_data['weather.freudenst'].forecast[14].datetime }}
