# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /config/www/community/lovelace-card-mod/card-mod.js

# Text to speech
tts:
  - platform: google_translate
#---------------------------------------------------------------
homeassistant:
  name: Aach
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 640
  currency: EUR
  country: DE
  unit_system: metric
  time_zone: "Europe/Berlin"
  packages: !include_dir_named custom_packages

  #Workaround for Custom Sensors for Energy Dashboard
  customize_glob:
    sensor.*_energy:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: energy
      state_class: total_increasing
    sensor.trinkwasser:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: "water"
      state_class: total_increasing

# Web Access Config
http:
  server_port: 443

# ADS Config
ads:
  ip_address: !secret beckhoff_ip
  device: !secret beckhoff_ads_device
  port: !secret beckhoff_ads_port

#------------------ Other Includes ----------------------
light: !include_dir_merge_list custom_light
cover: !include_dir_merge_list custom_cover
sensor: !include_dir_merge_list custom_sensor
binary_sensor: !include_dir_merge_list custom_binarySensor
lock: !include_dir_merge_list custom_lock
alarm_control_panel: !include_dir_merge_list custom_secPanel
notify: !include notify.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
climate: !include_dir_merge_list custom_climate
