# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /config/www/community/lovelace-card-mod/card-mod.js

# Text to speech
tts:
  - platform: google_translate
#---------------------------------------------------------------
homeassistant:
  name: Aach
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 640
  currency: EUR
  country: DE
  unit_system: metric
  time_zone: "Europe/Berlin"

  #Workaround for Custom Sensors for Energy Dashboard
  customize_glob:
    sensor.*_energy:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: energy
      state_class: total_increasing
    sensor.trinkwasser:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: "water"
      state_class: total_increasing

# Web Access Config
http:
  server_port: 443

# ADS Config
ads:
  ip_address: !secret beckhoff_ip
  device: !secret beckhoff_ads_device
  port: !secret beckhoff_ads_port

# Example configuration.yaml entry for iCloud, calendars will be found automatically
calendar:
  - platform: caldav
    username: !secret userIcloud
    password: !secret passIcloud
    url: https://caldav.icloud.com

#------------------ Other Includes ----------------------
light: !include_dir_merge_list custom_light
cover: !include_dir_merge_list custom_cover
sensor: !include_dir_merge_list custom_sensor
binary_sensor: !include_dir_merge_list custom_binarySensor
modbus: !include_dir_merge_list custom_modbus
lock: !include_dir_merge_list custom_lock
alarm_control_panel: !include_dir_merge_list custom_secPanel
notify: !include notify.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
climate: !include_dir_merge_list custom_climate

## Weather based template trigger to send esphome devices data
template:
  - trigger:
      - trigger: time_pattern
        minutes: "1"
    action:
      - action: weather.get_forecasts
        data:
          type: hourly
        target:
          entity_id: weather.freudenstadt
        response_variable: forecast_data
    sensor:
      - name: "Forecast (4h) Temperature"
        unique_id: forecast_4h_temperature
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[6].temperature }}
      - name: "Forecast (4h) Condition"
        unique_id: forecast_4h_condition
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[6].condition }}
      - name: "Forecast (4h) Wind Speed"
        unique_id: forecast_4h_wind_speed
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[6].wind_speed }}
      - name: "Forecast (4h) Wind Gust Speed"
        unique_id: forecast_4h_wind_gust_speed
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[6].wind_gust_speed }}
      - name: "Forecast (4h) Precipitation"
        unique_id: forecast_4h_precipitation
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[6].precipitation }}
      - name: "Forecast (4h) Timestamp"
        unique_id: forecast_4h_timestamp
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[6].datetime }}

      - name: "Forecast (8h) Temperature"
        unique_id: forecast_8h_temperature
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[10].temperature }}
      - name: "Forecast (8h) Condition"
        unique_id: forecast_8h_condition
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[10].condition }}
      - name: "Forecast (8h) Wind Speed"
        unique_id: forecast_8h_wind_speed
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[10].wind_speed }}
      - name: "Forecast (8h) Wind Gust Speed"
        unique_id: forecast_8h_wind_gust_speed
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[10].wind_gust_speed }}
      - name: "Forecast (8h) Precipitation"
        unique_id: forecast_8h_precipitation
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[10].precipitation }}
      - name: "Forecast (8h) Timestamp"
        unique_id: forecast_8h_timestamp
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[10].datetime }}

      - name: "Forecast (12h) Temperature"
        unique_id: forecast_12h_temperature
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[14].temperature }}
      - name: "Forecast (12h) Condition"
        unique_id: forecast_12h_condition
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[14].condition }}
      - name: "Forecast (12h) Wind Speed"
        unique_id: forecast_12h_wind_speed
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[14].wind_speed }}
      - name: "Forecast (12h) Wind Gust Speed"
        unique_id: forecast_12h_wind_gust_speed
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[14].wind_gust_speed }}
      - name: "Forecast (12h) Precipitation"
        unique_id: forecast_12h_precipitation
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[14].precipitation }}
      - name: "Forecast (12h) Timestamp"
        unique_id: forecast_12h_timestamp
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[14].datetime }}

  - trigger:
      - trigger: time_pattern
        minutes: "5"
    action:
      - action: weather.get_forecasts
        data:
          type: daily
        target:
          entity_id: weather.freudenstadt
        response_variable: forecast_data
    sensor:
      - name: "Forecast Weather Max Temp today"
        unique_id: forecast_weather_max_temp_today
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[0].temperature }}
      - name: "Forecast Weather Min Temp today"
        unique_id: forecast_weather_min_temp_today
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[0].templow }}
      - name: "Forecast Weather Wind today"
        unique_id: forecast_weather_wind_today
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[0].wind_speed }}
      - name: "Forecast Weather Regen today"
        unique_id: forecast_weather_regen_today
        state: >
          {{ forecast_data['weather.freudenstadt'].forecast[0].precipitation }}

  - trigger:
      trigger: time_pattern
      minutes: /30 # aktualisiert alle 30 Minuten
    action:
      - action: calendar.get_events
        target:
          entity_id: calendar.abfall
        data:
          start_date_time: "{{ (now().date() + timedelta(days=0)).isoformat() }}T06:00:00"
          duration:
            hours: 18
            minutes: 0
            seconds: 0
        response_variable: agenda
      - variables:
          events: "{{ agenda['calendar.abfall']['events'] }}"
    sensor:
      - name: "Abfalltermine Heute"
        unique_id: trash_calendar_events_today
        state: >
          {%- set summaries = events | map(attribute='summary') | list -%}
          {{ summaries | join(' + ') if summaries else '-' }}
        attributes:
          count: "{{ summaries | count }}"
          titles: "{{ summaries }}"
  - trigger:
      trigger: time_pattern
      minutes: /30 # alle 30 Minuten aktualisieren
    action:
      - action: calendar.get_events
        target:
          entity_id: calendar.abfall
        data:
          start_date_time: "{{ (now().date() + timedelta(days=1)).isoformat() }}T06:00:00"
          duration:
            hours: 18
            minutes: 0
            seconds: 0
        response_variable: agenda
      - variables:
          events: "{{ agenda['calendar.abfall']['events'] }}"
    sensor:
      - name: "Abfalltermine Morgen"
        unique_id: trash_calendar_events_tomorrow
        state: >
          {%- set summaries = events | map(attribute='summary') | list -%}
          {{ summaries | join(' + ') if summaries else '-' }}
        attributes:
          count: "{{ summaries | count }}"
          titles: "{{ summaries }}"
