# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate
#---------------------------------------------------------------
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 640
  currency: EUR
  country: DE
  unit_system: metric
  time_zone: "Europe/Berlin"

  #Workaround for Custom Sensors for Energy Dashboard
  customize_glob:
    sensor.*_energy:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: energy
      state_class: total_increasing
    sensor.trinkwasser:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: "water"
      state_class: total_increasing

# Web Access Config
http:
  server_port: 443

#------------------ Notification Groups --------------------
notify:
  - name: ALL_Devices
    platform: group
    services:
      - service: mobile_app_riphone
      - service: mobile_app_babsisiphone
      - service: mobile_app_ipad
  - name: Benny
    platform: group
    services:
      - service: mobile_app_riphone
  - name: Babsi
    platform: group
    services:
      - service: mobile_app_babsisiphone

#------------------ Other Includes ----------------------
light: !include_dir_merge_list custom_light
cover: !include_dir_merge_list custom_cover
sensor: !include_dir_merge_list custom_sensor
modbus: !include_dir_merge_list custom_modbus
lock: !include_dir_merge_list custom_lock
alarm_control_panel: !include_dir_merge_list custom_secPanel
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
