esphome:
  name: iot-wifi
  friendly_name: IOT Wifi

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Wo6+13Kp6+FdiWSLxmjC+809YQa7rpj9W6q/IFow2pY="

ota:
  - platform: esphome
    password: "fce836d9ecbf19db824dab0f10ca6b34"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Iot-Wifi Fallback Hotspot"
    password: "2kTNE6rpf2xF"

captive_portal:
    