esphome:
  name: tsp-display-eg
  friendly_name: tsp-display-eg

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "p8NdKM2B3kH4ASNjawnEUo+nUQ6k20V1Y8Y4/u1/+7o="

ota:
  - platform: esphome
    password: "b8c22fe3b23e480d00ca5f61f8c7d294"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tsp-Display-Eg Fallback Hotspot"
    password: "EZbTvo3CaHuz"

captive_portal:

font:
  - file: 'fonts/GothamRnd-Book.ttf'
    id: font1
    size: 8

# Pins for Waveshare ePaper ESP Board
spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14


# Now render everything on the ePaper screen.
display:
  - platform: waveshare_epaper
    id: eink_display
    cs_pin: GPIO15
    dc_pin: GPIO27
    busy_pin: GPIO25
    reset_pin: GPIO26
    reset_duration: 2ms
    model: 7.50inV2
    update_interval: never
    rotation: 90°
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");