- platform: climate_template
  name: "Büro_template"
  unique_id: "Büro_template"
  hvac_modes:
    - "heat"
    - "off"
  min_temp: 17
  max_temp: 23
  current_temperature_template: "{{ states('sensor.temperatur_buro') }}"
  target_temperature_template: "{{ states('sensor.zieltemperatur_buro') }}"
  hvac_mode_template: "{{ iif(is_state('switch.zusatzheizungen_buro', 'on'), 'heat', 'off') }}"
  set_hvac_mode:
    service: modbus.write_register
    data_template:
      hub: WGT
      unit: 1
      address: 442
      value: "{{ [iif(hvac_mode == 'heat', 1, 0)] }}"
  set_temperature:
    service: modbus.write_register
    data_template:
      hub: WGT
      unit: 1
      address: 402
      value: "{{ [temperature * 10] }}"
