- platform: template
  panels:
    alarm_panel_home:
      #      value_template: "{{ }}"
      arm_away:
        action: switch.turn_on
        target:
          entity_id: switch.mb_testalarm_esszimmertisch
        data:
          code: !secret alarm_code
      arm_home:
        action: switch.turn_on
        target:
          entity_id: switch.mb_testalarm_esszimmertisch
        data:
          code: !secret alarm_code
      disarm:
        - condition: state
          entity_id: device_tracker.riphone15
          state: "home"
        - action: switch.turn_off
          target:
            entity_id: switch.mb_testalarm_esszimmertisch
          data:
            code: !secret alarm_code

    alarm_panel_garage:
      #      value_template: "{{ }}"
      arm_away:
        action: switch.turn_on
        target:
          entity_id: switch.mb_testalarm_esszimmertisch
        data:
          code: !secret alarm_code
      arm_home:
        action: switch.turn_on
        target:
          entity_id: switch.mb_testalarm_esszimmertisch
        data:
          code: !secret alarm_code
      disarm:
        - condition: state
          entity_id: device_tracker.riphone15
          state: "home"
        - action: switch.turn_off
          target:
            entity_id: switch.mb_testalarm_esszimmertisch
          data:
            code: !secret alarm_code
