- platform: ads
  name: "ads_WetterTEMP"
  adsvar: gvl_ha.diWetterTEMP
  unit_of_measurement: "°C"
  adstype: dint
  factor: 10
  state_class: measurement
- platform: ads
  name: "ads_WetterHUM"
  adsvar: gvl_ha.diWetterHUM
  unit_of_measurement: "%"
  adstype: dint
  state_class: measurement
- platform: ads
  name: "ads_WetterRAIN"
  adsvar: gvl_ha.wWetterRAIN
  unit_of_measurement: "mm"
  device_class: water
  state_class: TOTAL_INCREASING
  adstype: word
  factor: 10
- platform: ads
  name: "ads_WetterWINDspeed"
  adsvar: gvl_ha.diWetterWINDspeed
  unit_of_measurement: "km/h"
  adstype: dint
  factor: 10
  state_class: measurement
- platform: ads
  name: "ads_WetterWINDdir"
  adsvar: gvl_ha.diWetterWINDdir
  unit_of_measurement: "°"
  adstype: dint
  state_class: measurement
- platform: ads
  name: "ads_WetterLUX"
  adsvar: gvl_ha.diWetterLUX
  unit_of_measurement: "lx"
  adstype: dint
  state_class: measurement
