- platform: ads
  name: "ads_WetterTEMP"
  adsvar: gvl_ha.diWetterTEMP
  unit_of_measurement: "°C"
  device_class: temperature
  adstype: dint
  factor: 10
  state_class: measurement
- platform: ads
  name: "ads_WetterHUM"
  device_class: humidity
  adsvar: gvl_ha.diWetterHUM
  unit_of_measurement: "%"
  adstype: dint
  state_class: measurement
- platform: ads
  name: "ads_WetterRAIN"
  adsvar: gvl_ha.wWetterRAIN
  unit_of_measurement: "mm"
  device_class: water
  state_class: TOTAL_INCREASING
  adstype: word
  factor: 10
- platform: ads
  name: "ads_WetterWINDspeed"
  adsvar: gvl_ha.diWetterWINDspeed
  unit_of_measurement: "km/h"
  adstype: dint
  factor: 10
  state_class: measurement
- platform: ads
  name: "ads_WetterWINDdir"
  adsvar: gvl_ha.diWetterWINDdir
  unit_of_measurement: "°"
  adstype: dint
  state_class: measurement_angle
- platform: ads
  name: "ads_WetterLUXabove"
  adsvar: gvl_ha.diWetterLUXabove
  unit_of_measurement: "lx"
  adstype: dint
  state_class: measurement
- platform: ads
  name: "ads_WetterLUXwest"
  adsvar: gvl_ha.diWetterLUXwest
  unit_of_measurement: "lx"
  adstype: dint
  state_class: measurement
- platform: ads
  name: "ads_GiftschrankWerkstatt_Temp"
  adsvar: gvl_ea.iPT100W01_1
  unit_of_measurement: "°C"
  adstype: int
  factor: 10
  state_class: measurement
