- platform: ads
  name: "Wetterstation_Temp"
  adsvar: gvl_mb.Output_Registers[26]
  unit_of_measurement: "°C"
  adstype: word
  factor: 10
- platform: ads
  name: "Wetterstation_relHum"
  adsvar: gvl_mb.Output_Registers[27]
  unit_of_measurement: "%"
  adstype: word
- platform: ads
  name: "Wetterstation_Regenmenge"
  adsvar: gvl_mb.Output_Registers[28]
  unit_of_measurement: "mm"
  adstype: word
  factor: 10
- platform: ads
  name: "WindspeedMS"
  adsvar: gvl_mb.Output_Registers[29]
  unit_of_measurement: "m/s"
  adstype: word
  factor: 10
- platform: ads
  name: "WindspeedKMH"
  adsvar: gvl_mb.Output_Registers[30]
  unit_of_measurement: "km/h"
  adstype: word
  factor: 10
- platform: ads
  name: "WindDirectionDegree"
  adsvar: gvl_mb.Output_Registers[31]
  unit_of_measurement: "°"
  adstype: word
