# Board: Espressif ESP32-H2-DevKit
# Definition: definitions/boards/esp32-h2-devkitm-1/manifest.yaml

esphome:
  name: esp-thrd-bett-eltern
  friendly_name: esp-thrd-bett-eltern

esp32:
  variant: esp32h2

logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_key

# Example OpenThread configuration (ESP32)
network:
  enable_ipv6: true

openthread:
  force_dataset: true
  tlv: !secret thread_tlv
