package_security:
  template:
    - alarm_control_panel:
        - arm_away:
            - action: switch.turn_on
              target:
                entity_id:
                  - switch.mb_testalarm_esszimmertisch
          arm_home:
            - action: switch.turn_on
              target:
                entity_id:
                  - switch.mb_testalarm_esszimmertisch
          disarm:
            - condition: state
              entity_id:
                - device_tracker.riphone15
              state: home
              match: all
            - action: switch.turn_off
              target:
                entity_id:
                  - switch.mb_testalarm_esszimmertisch
          code_arm_required: true
          code_format: number
          default_entity_id: alarm_control_panel.alarm_panel_home
          name: alarm_panel_home
          unique_id: "alarm_panel_home"
    - alarm_control_panel:
        - arm_away:
            - action: switch.turn_on
              target:
                entity_id:
                  - switch.mb_testalarm_esszimmertisch
          arm_home:
            - action: switch.turn_on
              target:
                entity_id:
                  - switch.mb_testalarm_esszimmertisch
          disarm:
            - condition: state
              entity_id:
                - device_tracker.riphone15
              state: home
              match: all
            - action: switch.turn_off
              target:
                entity_id:
                  - switch.mb_testalarm_esszimmertisch
          code_arm_required: true
          code_format: number
          default_entity_id: alarm_control_panel.alarm_panel_garage
          name: alarm_panel_garage
          unique_id: "alarm_panel_garage"
