- platform: template
  lights:
    mb_esszimmertisch:
      friendly_name: "Esszimmertisch"
      value_template: "{{ (states('binary_sensor.mb_light_esszimmertisch_status')) }}"
      level_template: "{{ (states('sensor.mb_light_esszimmertisch_bright') | int(0) ) }}"
      turn_on:
        - service: modbus.write_coil
          data_template:
            hub: "Beckhoff"
            unit: 1
            address: 1007
            state: TRUE
      turn_off:
        - service: modbus.write_coil
          data_template:
            hub: "Beckhoff"
            unit: 1
            address: 1007
            state: FALSE
      set_level:
        - service: modbus.write_register
          data_template:
            hub: "Beckhoff"
            unit: 1
            address: 2007
            value: "{{ brightness }}"
    mb_esszimmer:
      friendly_name: "Esszimmer"
      value_template: "{{ (states('binary_sensor.mb_light_esszimmer_status')) }}"
      level_template: "{{ (states('sensor.mb_light_esszimmer_bright') | int(0) ) }}"
      turn_on:
        - service: modbus.write_coil
          data_template:
            hub: "Beckhoff"
            unit: 1
            address: 1008
            state: TRUE
      turn_off:
        - service: modbus.write_coil
          data_template:
            hub: "Beckhoff"
            unit: 1
            address: 1008
            state: FALSE
      set_level:
        - service: modbus.write_register
          data_template:
            hub: "Beckhoff"
            unit: 1
            address: 2008
            value: "{{ brightness }}"
    mb_wohnzimmer:
      friendly_name: "Wohnzimmer"
      value_template: "{{ (states('binary_sensor.mb_light_wohnzimmer_status')) }}"
      level_template: "{{ (states('sensor.mb_light_wohnzimmer_bright') | int(0) ) }}"
      turn_on:
        - service: modbus.write_coil
          data_template:
            hub: "Beckhoff"
            unit: 1
            address: 1009
            state: TRUE
      turn_off:
        - service: modbus.write_coil
          data_template:
            hub: "Beckhoff"
            unit: 1
            address: 1009
            state: FALSE
      set_level:
        - service: modbus.write_register
          data_template:
            hub: "Beckhoff"
            unit: 1
            address: 2009
            value: "{{ brightness }}"
    mb_balkon:
      friendly_name: "Balkon"
      value_template: "{{ (states('binary_sensor.mb_light_balkon_status')) }}"
      level_template: "{{ (states('sensor.mb_light_balkon_bright') | int(0) ) }}"
      turn_on:
        - service: modbus.write_coil
          data_template:
            hub: "Beckhoff"
            unit: 1
            address: 1010
            state: TRUE
      turn_off:
        - service: modbus.write_coil
          data_template:
            hub: "Beckhoff"
            unit: 1
            address: 1010
            state: FALSE
      set_level:
        - service: modbus.write_register
          data_template:
            hub: "Beckhoff"
            unit: 1
            address: 2010
            value: "{{ brightness }}"
